[project]
name = "automacao-noteboklm"
version = "0.1.0"
description = "Automação para inserir links em interface gráfica usando PyAutoGUI. Lê links de um arquivo e simula cliques e digitação."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyautogui>=0.9.54",
]
